name: Morning Greeting

on:
  schedule:
    - cron: '0 7 * * *'   # 9:00 AM Paris (UTC+2). Change if needed.
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          quote=$(curl -s https://zenquotes.io/api/random | jq -r '.[0].q + " — " + .[0].a')
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🌅 **Good morning, Sam!**\\n💡 $quote\"}" \
               "${{ secrets.DISCORD_WEBHOOK_URL }}?wait=true"
